### ISSUE TITLE
Allow to attach partials to a crate?

### ISSUE THREAD

**Issue by kinow** [ResearchObject/ro-crate-py#146]
Hi,

For Autosubmit, since the workflow configuration doesn't contain the information needed for RO-Crate, I [used](https://earth.bsc.es/gitlab/es/autosubmit/-/merge_requests/317) the exact same approach from [COMPSs](https://github.com/bsc-wdc/compss/blob/9e79542eef60afa9e288e7246e697bd7ac42db08/compss/runtime/scripts/system/provenance/generate_COMPSs_RO-Crate.py) and asked users to provide a YAML file with authors & license.

Then I create the objects and attach/add to the RO-Crate-py object.

The implementation in Autosubmit is similar, but not identical to COMPSs. Other workflow managers with similar need may craft yet another way of doing the same.

It would be nice if there was a way to load RO-Crate-py entities directly from a dictionary/YAML data. Something like

```py

from rocrate.entities.person import Person

crate = ROCrate()

with open('') as f:
  yaml_content = parser.safe_load(f)

for author in yaml_content['authors']:
  crate.add(Person.load_from_dict(author)
```

Not sure how to validate the format of the entities... maybe instead of YAML receive JSON-LD directly, or provide a tool/script to read SPARQL+SHACL, etc.?

Cheers
Bruno

**Comment by simleo** [comment]
I don't think this is feasible, mainly because RO-Crate is not just about entities but also their relationships. Suppose you somehow loaded authors from a file like this:

```json
[
    {
        "@id": "https://orcid.org/0000-0002-1825-0097",
        "@type": "Person",
        "name": "Josiah Carberry"
    },
    {
        "@id": "https://orcid.org/0000-0000-0000-0000",
        "@type": "Person",
        "name": "John Doe"
    }
]
```

What do you link them to? What's the crate entity that was authored by these persons? You'd need a way to express that, but the user that writes the above file does not even know they're going to end up in an RO-Crate. Even if that was doable, you'd be basically asking users to write full RO-Crate markup. The engine's code that's generating the RO-Crate is the only one who has all the knowledge to make sense of the whole thing.

**Comment by stain** [comment]
See from @dgarijo @PavelAntonia approach on https://github.com/oeg-upm/ya2ro on using a YAML template for making an RO-Crate, which can even look up ORCIDs,  e.g.:

```yaml
type: "paper"

title: "DockerPedia: A Knowledge Graph of Software Images and their Metadata"

authors:
  - # Daniel Garijo
    orcid: http://orcid.org/0000-0003-0454-7145
    role: "Researcher"
  -
    name: "Maximiliano Osorio"
    position: "Research Programmer"
    description: "Computer Scientist at the Information Sciences Institute of the University of Southern California."
```

Could this be used to create a skeleton RO-Crate that then is augmented by the Autosubmit code?
